// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxhHR2k0R0pBtKjBvNlIsLbrUDBkjHiXM',
    appId: '1:479824674507:web:54bb07559ff7ac16d8254e',
    messagingSenderId: '479824674507',
    projectId: 'masrofatak',
    authDomain: 'masrofatak.firebaseapp.com',
    storageBucket: 'masrofatak.appspot.com',
    measurementId: 'G-KEM6XD260B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJa2GaBAT7U2dvfKzHK0f8-HJN6dxenXQ',
    appId: '1:479824674507:android:db4e77048a59e0f8d8254e',
    messagingSenderId: '479824674507',
    projectId: 'masrofatak',
    storageBucket: 'masrofatak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3j1ud6vavrZg_Fyz6cB8RAU2JBPfFwSI',
    appId: '1:479824674507:ios:03df168c825f7232d8254e',
    messagingSenderId: '479824674507',
    projectId: 'masrofatak',
    storageBucket: 'masrofatak.appspot.com',
    iosClientId: '479824674507-mpknkj4n9jf23svapgsmgvu3610d165p.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrofatak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3j1ud6vavrZg_Fyz6cB8RAU2JBPfFwSI',
    appId: '1:479824674507:ios:d5d250163aa6d099d8254e',
    messagingSenderId: '479824674507',
    projectId: 'masrofatak',
    storageBucket: 'masrofatak.appspot.com',
    iosClientId: '479824674507-9s3d4hud414mgoeql25dm84p1iivv4t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.masrofatak.RunnerTests',
  );
}
